"""create orders table

Revision ID: e476323ff69f
Revises: 
Create Date: 2024-08-06 21:14:37.089630

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e476323ff69f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("apartment_number", sa.Integer(), nullable=False),
        sa.Column("petname", sa.String(), nullable=False),
        sa.Column("breed", sa.String(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("walk_datetime", sa.DateTime(), nullable=False),
        sa.Column("walker", sa.Enum("Petr", "Anton", name="walker"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
